LegalMate/hyacinth

- hyacinth/session.py
Adds `ratelimit` optional parameter to `hyacinth.Session`, defaulted to `False`. Setting `ratelimit` to `True` will cause all of the Session's HTTP requests to be rate limited according to Clio's rate limit scheme.
Usage:
```python
s = hyacinth.Session(client_id=clio_client_id,
client_secret=clio_client_secret,
token=token,
ratelimit=True)
```
```python
for i in range(0, 100):
print(s.get_who_am_i())
```
```python
{'data': {'id': 350963386, 'etag': '"14eb46ba60ce9c2e6a68f6d0d2c36334"', 'name': 'Anson MacKeracher'}}
{'data': {'id': 350963386, 'etag': '"14eb46ba60ce9c2e6a68f6d0d2c36334"', 'name': 'Anson MacKeracher'}}
...
Sleeping for 56s
{'data': {'id': 350963386, 'etag': '"14eb46ba60ce9c2e6a68f6d0d2c36334"', 'name': 'Anson MacKeracher'}}
...
```
> L-156: Basic support for API rate limits

- hyacinth/__init__.py
- hyacinth/session.py
Adds (optional) support for `requests` [`raise_for_status`](https://requests.readthedocs.io/en/latest/api/#requests.Response.raise_for_status), which will raise an exception for any non-200 HTTP `status_code`.
Usage:
```python
>> s = hyacinth.Session(token=<...>, client_id=<...>, client_secret=<...>, raise_for_status=True)
>> s.get_user(id="not_a_real_user")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/amackera/projects/hyacinth/hyacinth/session.py", line 124, in get_user
return self.__get_resource(url, **kwargs)
File "/Users/amackera/projects/hyacinth/hyacinth/session.py", line 17, in wrapper
resp = f(self, *args, **kwargs)
File "/Users/amackera/projects/hyacinth/hyacinth/session.py", line 70, in __get_resource
r.raise_for_status()
File …
```
> L-313: Error handling

- hyacinth/session.py
Rate limits will be logged, and logging will respect whatever logging setup has been configured on the parent app using `hyacinth`:
It looks like this in the console:
```python
amackera@vanaheim hyacinth % poetry run python test.py
INFO:hyacinth.session:Clio Rate Limit hit, Retry-After: 73s
```
> L-408: Fix rate limit logging

- hyacinth/session.py
It was still using the old style of `fields=`.
> L-572: Fix upload_document bug with params

- hyacinth/session.py
Adds new `upload_document_async` async implementation of upload document to Clio.
(note: this adds async uploads to **normal** document uploads. Async mutlipart document uploads are already in place.
> L-662: Implement upload_document_async

- hyacinth/async_session.py
- hyacinth/session.py
This increases the HTTP PUT request timeout when uploading documents. Implements a 10 minute timeout for the synchronous client, and a 1 hour long timeout for the async client.
> L-726: Increase PUT timeout for clio_async_session.upload_document

- .gitignore
- hyacinth/session.py
This PR adds the ability to include `fields="example_field"` to `post_webhook`.
> L-742: Add model specific fields to be returned in webhooks we create

- hyacinth/session.py
Very small addition of including the `expires_at` parameter in the request body for `post_webhook`. What's missing is a way to refresh that expiration time as the max we can include is 31 days at a time.
I've made it optional so as not to break other places that are using the endpoint currently.
> L-814: Add expires_at to post_webhook, but it is optional

- hyacinth/session.py
- test/test_session.py
Adds `delete_webhook` functionality. Calls an HTTP `DELETE` on the provided webhook resource ID.
> L-1015: DELETE Webhook

- hyacinth/session.py
Small PR to return expires_at for new webhook POST requests.
> L-1384: POSTing new webhook should return expires_at by default

- hyacinth/session.py
- test/test_session.py
Adds support for [Unlimited Cursor Pagination](https://docs.developers.clio.com/api-docs/paging/#unlimited-cursor-pagination), which allows us to continuously page for results beyond 10,000 records.
> L-1404: Hyacinth should support unlimited cursor pagination

- hyacinth/session.py
Adds `get_folders_content()` fn to [retrieve the content of a Folder](https://docs.developers.clio.com/api-reference/#tag/Folders/operation/Folder#list).
> L-1534: Add get_folders_content to hyacinth

- hyacinth/async_session.py
- hyacinth/session.py
Adds new args to `Session.upload_document`, `Session.upload_document_async`, and `AsyncSession.upload_document` for `document_category_id`.
> L-1544: Add support for specifying document_category for document upload

- hyacinth/session.py
- test/test_session.py
Alter how `get_paginated_resource` works to enable workflows that don't require automatic pagination.
- Adds new option to Hyacinth session: `autopaginate` (defaults to `True` for backwards compatibility)
- Make public functions out of `__get_resource`, `__get_paginated_resource`, `__post_resource`, `__patch_resource`, `__delete_resource`
- It `autopaginate` is `False`, any paginated resources will yield **one** _**whole page**_ of resources. The assumption is that you can manually follow the next page link.
> L-1657: Alter hyacinth to optionally not follow pagination

- hyacinth/session.py
This PR introduces support for the following:
* GET all `Task Template Lists`
* GET a single `Task Template List`
* POST a new `Task Template List`
* PATCH a single `Task Template List`
* DELETE a single `Task Template List`
> L-1929: Partial support for Task Template Lists

- hyacinth/async_session.py
- hyacinth/session.py
* Adding `POST` to the `trust_requests` endpoint in both the synchronous and asynchronous clients
> L-3081: Add POST trust requests

- hyacinth/session.py
> L-3113: Add log when Clio responds with b64 encoded rate limit message

- hyacinth/async_session.py
* The client we're using already gives us the string
> L-3180: Fix for logging errors in async client

- hyacinth/async_session.py
* Check if the redirect URL is s3 and handle appropriately
> L-3230: Handle redirects from Clio to S3 in async client

- hyacinth/async_session.py
- hyacinth/session.py
This pull request introduces new methods to handle document categories in both asynchronous and synchronous sessions. The changes include adding methods to get, post, patch, and delete document categories.
* [`hyacinth/async_session.py`](diffhunk://#diff-bf70adb2d1202972e037610d4b00d7b943ac257db1dab8dde364c8198dabb7d6R799-R823): Added methods `get_document_categories`, `get_document_category`, `patch_document_category`, and `delete_document_category` to handle document categories.
* [`hyacinth/session.py`](diffhunk://#diff-053453a468dda5756e7c5fe302404cfed3adbcdfc96dd28f67bf88aafb295b80L294-R318): Added methods `get_document_categories`, `get_document_category`, `post_document_category`, `patch_document_category`, and `delete_document_category` to handle document categories.
> L-3374: Full support for DocumentCategories

- hyacinth/async_session.py
- hyacinth/session.py
This pull request includes changes to the `post_folder` method in both the `hyacinth/async_session.py` and `hyacinth/session.py` files. The changes add an optional `document_category_id` parameter to the method, allowing the inclusion of a document category when creating a new folder.
Changes to `post_folder` method:
* [`hyacinth/async_session.py`](diffhunk://#diff-bf70adb2d1202972e037610d4b00d7b943ac257db1dab8dde364c8198dabb7d6L429-R441): Added an optional `document_category_id` parameter to the `post_folder` method and included it in the JSON payload if provided.
* [`hyacinth/session.py`](diffhunk://#diff-053453a468dda5756e7c5fe302404cfed3adbcdfc96dd28f67bf88aafb295b80L409-R421): Added an optional `document_category_id` parameter to the `post_folder` method and included it in the JSON …
> L-3375: Support including DocumentCategories when POSTing folders
