LegalMate/hyacinth

hyacinth/__init__.py
hyacinth/session.py

…d paginated resource needed correct fn name for __get_resource

nfranchise/l-315 Bug fix for rate limit wrapper and paginated resource

---

.github/workflows/basic.yml
README.md
poetry.lock
pyproject.toml
test/__init__.py
test/test_session.py

Run the tests via:
```sh
poetry run test
```

L-301: Fix tests

---

.github/workflows/basic.yml
README.md
hyacinth/session.py
poetry.lock
pyproject.toml
test/test_session.py

Adds support for `update_token` feature of Authlib (auto-refresh tokens).

L-545: Save new OAuth2 tokens after refresh

---

hyacinth/session.py

L-597: Support for creating matters, activities, and activity descriptions

---

hyacinth/session.py

Deletes document with an ID. Tested it and it worked

added delete document function

---

hyacinth/session.py

This PR fixes some mistakes I found for Line Items endpoints and introduces support for Custom Actions.

L-864: Fix for some previously added endpoints and support for Custom Actions.

---

hyacinth/session.py
test/test_session.py

Add `update_webhook` to Session.

L-1140: PATCH Webhook

---

hyacinth/session.py

Adds GET fns for getting an individual webhook, or a list of webhooks.

L-180: GET Webhook, Webhooks

---

hyacinth/session.py

The problem seemed to be with a certain number of items (ie. contacts), the amount of requests grew to a point of hitting the rate limits and it looked like it was repeating some requests multiple times.

L-1689 Bug fix for get_autopaginated_resource

---

hyacinth/session.py

Adding support for:
* Getting all Tasks
* Get a single Task
* Patch a single Task
* Delete a single Task

L-1804: Adding full support for Tasks endpoints

---

hyacinth/session.py

Adding support for creating a new Task List.

L-1921: Add POST task list

---

hyacinth/session.py

Add support for:
* GET all `practice_areas`
* GET a `practice_area`
* POST a `practice_area`
* PATCH a `practice_area`
* DELETE a `practice_area`

L-1232: Add support for practice_areas

---

hyacinth/session.py

[Get client of matter user matter id](https://docs.developers.clio.com/api-reference/#tag/Clients)

L-2893: Add GET matter client

---

hyacinth/session.py

L-2911: Bug: Infrequent base64 encoded API responses from Clio cause errors in our response processing
This PR (hopefully) fixes an issue that arises occasionally with the Clio API whereby it will return an atypical rate limit indication response.

L-2911: Bug: Infrequent base64 encoded API responses from Clio cause errors in our response processing

---

hyacinth/session.py

* Add support for all `Communication` endpoints

L-2956: Support for Clio Communication model

---

hyacinth/async_session.py
hyacinth/session.py

* Update the `ratelimit` wrapper and class methods to match the sync version of hyacinth
* Add `get_contacts` to the Async hyacinth

L-3059: Update and expand AsyncSession

---

hyacinth/async_session.py
hyacinth/session.py

L-3094: Add Reminder endpoints + port over task endpoints to async hyacinth

---

hyacinth/async_session.py

* made activity related methods in async class

L-3167 make activity related methods for async class

---

hyacinth/async_session.py
hyacinth/session.py

- added get and get_paginated requests in both async_session and session for Custom Field Sets

L-3443: Added getters for Custom Field Sets

---

hyacinth/async_session.py

L-3618: Pagination debugging and remove NullHandler

---

hyacinth/async_session.py

L-3619: Fix pagination when using httpx 0.28.x
